# Generated by Django 3.1.3 on 2020-11-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTodoTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='タスク名')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了フラグ')),
            ],
            options={
                'db_table': 't_todo_task',
            },
        ),
    ]
